using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Networking;
using System.Collections;
using TMPro;

public class SelectAvatar : MonoBehaviour
{
    public GameObject khung1_1;
    public GameObject khung1_2;
    public GameObject khung1_3;
    public GameObject khung1_4;
    public GameObject khung2_1;
    public GameObject khung2_2;
    public GameObject khung2_3;
    public GameObject khung2_4;
    public GameObject khung3_1;
    public GameObject khung3_2;
    public GameObject khung3_3;
    public GameObject khung3_4;
    public GameObject khung4_1;
    public GameObject khung4_2;
    public GameObject khung4_3;
    public GameObject khung4_4;
    public GameObject khung5_1;
    public GameObject khung5_2;
    public GameObject khung5_3;
    public GameObject khung5_4;
    public GameObject khung6_1;
    public GameObject khung6_2;
    public GameObject khung6_3;
    public GameObject khung6_4;
    public GameObject khung7_1;
    public GameObject khung7_2;
    public GameObject khung7_3;
    public GameObject khung7_4;
    public GameObject khung8_1;
    public GameObject khung8_2;
    public GameObject khung8_3;
    public GameObject khung8_4;
    public GameObject khung9_1;
    public GameObject khung9_2;
    public GameObject khung9_3;
    public GameObject khung9_4;
    public GameObject khung10_1;
    public GameObject khung10_2;
    public GameObject khung10_3;
    public GameObject khung10_4;
    public void OnAvatarButtonClicked()
    {
        khung1_1.SetActive(true);
        khung1_2.SetActive(true);
        khung1_3.SetActive(true);
        khung1_4.SetActive(true);
        khung2_1.SetActive(false);
        khung2_2.SetActive(false);
        khung2_3.SetActive(false);
        khung2_4.SetActive(false);
        khung3_1.SetActive(false);
        khung3_2.SetActive(false);
        khung3_3.SetActive(false);
        khung3_4.SetActive(false);
        khung4_1.SetActive(false);
        khung4_2.SetActive(false);
        khung4_3.SetActive(false);
        khung4_4.SetActive(false);
        khung5_1.SetActive(false);
        khung5_2.SetActive(false);
        khung5_3.SetActive(false);
        khung5_4.SetActive(false);
        khung6_1.SetActive(false);
        khung6_2.SetActive(false);
        khung6_3.SetActive(false);
        khung6_4.SetActive(false);
        khung7_1.SetActive(false);
        khung7_2.SetActive(false);
        khung7_3.SetActive(false);
        khung7_4.SetActive(false);
        khung8_1.SetActive(false);
        khung8_2.SetActive(false);
        khung8_3.SetActive(false);
        khung8_4.SetActive(false);
        khung9_1.SetActive(false);
        khung9_2.SetActive(false);
        khung9_3.SetActive(false);
        khung9_4.SetActive(false);
        khung10_1.SetActive(false);
        khung10_2.SetActive(false);
        khung10_3.SetActive(false);
        khung10_4.SetActive(false);
    }
}
